### PR TITLE
use submodule for easier updates and set upstream to 0.10.0

### PR DESCRIPTION
**Pull request by ozzmos**

### CODE REVIEW

**Comment by M5oul** [comment]
Great idea for submodule of subtree!

**Comment by opi** [comment]
I'm not a huge fan of using git submodules, as I think it makes it hard to find exacly which upstream version is used. Does using submodules download the whole repository history ?

Maybe I'm old-fashionned, but a good old `wget https://github.com/asciimoo/searx/archive/v0.10.0.tar.gz` within the install script is pretty straight forward to me ;)

But thanks anyway, I have to take some times to test your PR in both cases (install and update)

**Comment by M5oul** [comment]
> Does using submodules download the whole repository history ?

Yep.

> Maybe I'm old-fashionned, but a good old wget https://github.com/asciimoo/searx/archive/v0.10.0.tar.gz within the install script is pretty straight forward to me ;)

Agree with that, I prefer that than sub{tree,module}.

**Comment by ozzmos** [comment]
@opi yes, it downloads the whole repository history. Inside the source directory, you can view logs, checkout for the searx project. 
I personally think it's easier for developers to test a specific version of Searx with submodule otherwise we need a branch for each searx version/install script.
Furthermore a archive can always be removed or altered.

**Comment by M5oul** [comment]
>it's easier for developers to test a specific version of Searx with submodule otherwise we need a branch for each searx version/install script.

Agree. But, I think, packages must stay on stable releases.
>Furthermore a archive can always be removed or altered.

In fact, but it's a rare case.


Finally, I am ok about using sub{tree,module} or releases archives.

**Comment by zamentur** [comment]
In 2.4.2, the current yunohost stable version, submodules are not supported by yunohost : see https://github.com/YunoHost/yunohost/pull/174 . Note with this PR all submodules history is downloaded. Subtrees are supported.
An argument about subtrees, is that the package could be installed without internet (yunohost local network use case).

**Pull request closed without merging**
