### PR TITLE
Upgrade to upstream version 0.12.0

### PR DESCRIPTION
**Pull request by JimboJoe**
## Problem
Upgrade to new Searx 0.12.0

## Solution
Update upstream archive reference and adapt setting file.

## PR Status
Work finished. Package_check, basic tests and upgrade from last version OK.
Could be reviewed and tested.

## Validation

- ~[ ] **Principle agreement** 0/2 :~
- ~[ ] **Quick review** 0/1 :~
- ~[ ] **Simple test** 0/1 :~
- ~[ ] **Deep review** 0/1 :~
- ~[ ] **Complex test** 0/0~
---
- [ ] ~**Complete test** :~
- [ ] ~**Upgrade previous version** :~
- [X] ~**Code review** : Maniack C~
- [X] ~**Approval (LGTM)** : Maniack C~
- [x] ~**Approval (LGTM)** : frju365~
- [X] ~**CI succeeded** : Maniack C~

Since this PR has been rerouted from master to testing. It passes to a minor decision.
- [ ] **Upgrade previous version** : 
- [x] **Code review** : Maniack C
- [x] **Approval (LGTM)** : Maniack C
- [x] **Approval (LGTM)** : frju365
- [x] **CI succeeded** : Maniack C
- [x] **CI succeeded** : [Build Status/badge/icon)](https://ci-apps-dev.yunohost.org/jenkins/job/searx_ynh%20enh_searx_0.12.0%20(Official)/)  
When the PR is mark as ready to merge, you have to wait for 3 days before really merge it.

### CODE REVIEW

**Comment by maniackcrudelis** [comment]
Just 2 questions:

- Why just me !?
- And, why do you want to review this PR on the official list instead of here. (just a question, because why not...)

Anyway, I like your template for this PR. Maybe it's can be our official template. We need one, by the way...

So, I tried a "real" install on my VM, it works fine.
And all the tests with Package check are good.

**Comment by JimboJoe** [comment]
As discussed on XMPP, it seems better to apply the complete process in the apps themselves, and then merge quickly the PR on official/community.json. So let's move on!

**Comment by maniackcrudelis** [comment]
If you don't mind, I slightlied change your the validation points. It seems more specific to the apps.
Reverse my changes if you don't agree with me.

**Comment by JimboJoe** [comment]
Obsoleted by https://github.com/YunoHost-Apps/searx_ynh/pull/21

**Pull request closed without merging**
