### PR TITLE
[enh] Update of the scripts

### LINKED ISSUE #19: Unable to install due to a Python version conflict
When attempting to install Searx, either from master or the `global_update` branch, I keep getting the following error:

    Downloading/unpacking cryptography>=1.3.4 (from pyopenssl==16.2.0->r /opt/yunohost/searx/requirements-ynh.txt (line 10))
      Running setup.py (path:/tmp/pip-build-H058kX/cryptography/setup.py) egg_info for package cryptography
        error in cryptography setup command: invalid environment marker: python_version < '3'

Apparently this is either an issue with `cryptography` wrongly attempting to use Python 3 instead of Python 2, or as another thread suggested a problem with `pip` and `setuptools`. I tried fixing it through the latter method, manually updating both packages through `pip`, but this resulted in the `yunohost` package ceasing to work entirely.

### PR DESCRIPTION
**Pull request by maniackcrudelis**
## Problem
- *Scripts are a little bit out of date*
- *Fix #19*

## Solution
- *Update of the scripts and helpers*

## PR Status
Work finished. Package_check OK.  
Could be reviewed and tested.

## Validation
*Minor decision*
- [x] **Upgrade previous version** : Maniack C
- [X] **Code review** : JimboJoe
- [X] **Approval (LGTM)** : JimboJoe
- [x] **Approval (LGTM)** : Scith
- [X] **CI succeeded** : JimboJoe
- [x] **CI succeeded** : [Build Status/badge/icon)](https://ci-apps-dev.yunohost.org/jenkins/job/searx_ynh%20global_update%20(Official)/)  
When the PR is mark as ready to merge, you have to wait for 3 days before really merge it.

### CODE REVIEW

**Comment by maniackcrudelis** [comment]
@YunoHost-Apps/apps-group

**Comment by maniackcrudelis** [comment]
I would really try an upgrade (maybe tomorrow), but at least I can say our CI seems really happy to have your fix !
https://ci-apps-dev.yunohost.org/jenkins/job/searx_ynh%20global_update%20(Official)/2/consoleFull

**Comment by maniackcrudelis** [comment]
Because we can't install searx from the current stable version of this package, I just tried an upgrade from my own searx version.
Quite a bit risky I know...
But I'm confident about the work of JimboJoe, and I was right about it.
The upgrade process works fine :)

**Comment by scith** [comment]
Looks good to me too 👍  Thanks for all your work refreshing the packages and bringing them up to standards

**Comment by frju365** [comment]
I'm a bit late... but I approve this changes too.

**Comment by maniackcrudelis** [comment]
Will be merged in 3 days.

**Pull request merged**
