### PR TITLE
Oups, PR conflict here !

### PR DESCRIPTION
**Pull request by maniackcrudelis**
2 PR at the same time, and we have duplicated this include.
To works fine, this include need to be at the end of the file.

- [x] Complete test
- [ ] Upgrade previous version
- [x] Code review
- [x] Approval (LGTM) JimboJoe
- [x] Approval (LGTM)
- [x] CI succeeded

[Minor decision](https://github.com/YunoHost/project-organization/blob/master/yunohost_project_organization.md#minor-decision), close on 13 of july, or 9 of july.

### CODE REVIEW

**Comment by frju365** [comment]
For me the PR doesn't need a complete test. Upgrade is perhaps enough for the long tests category.
For me : 
- [X] Code review

**Comment by maniackcrudelis** [comment]
I thought at a test of nginx.
Try an install and check if nginx still works fine and if the panel appears.

**Comment by frju365** [comment]
- [X] Complete test
Everything is ok and the panel appears (logo at the bottom)

**Comment by maniackcrudelis** [comment]
Nice ;)

I would like to perform a pcheck test. But, currently this new method doesn't allow the dev who make the PR to check the boxes.
I think we should think about that...

**Comment by frju365** [comment]
CI succeded is ok, no ?

**Comment by JimboJoe** [comment]
LGTM 👍

**Comment by maniackcrudelis** [comment]
> CI succeded is ok, no ?

No, our CI doesn't check the pull request.
So we have to perform this test on our own.

**Comment by maniackcrudelis** [comment]
> CI succeded is ok, no ?

No, our CI doesn't check the pull request.
So we have to perform this test on our own.

For what it's worth, I did a test.
https://paste.yunohost.org/idojidubif

**Comment by frju365** [comment]
- [X] CI Succeded test is ok, I think. I already have verified the test you did.

**Comment by JimboJoe** [comment]
@maniackcrudelis If you're OK, we could merge that, couldn't we?

**Comment by maniackcrudelis** [comment]
Yes we can, the upgrade test is not needed. We know that the nginx config will be rewrite by the upgrade.

**Pull request merged**
