### PR TITLE
Testing

### LINKED ISSUE #53: installation fails
installation fails
Could you have a look at the logs:
https://paste.yunohost.org/raw/ibolusevil
thanks for help

### PR DESCRIPTION
**Pull request by maniackcrudelis**
## Problem
- *Global upgrade of the package.*
- *Update to 0.15.0*
- *Fix #53*

## PR Status
- [x] Code finished.
- [x] Tested with Package_check.
- [x] Fix or enhancement tested.
- [x] Upgrade from last version tested.
- [x] Can be reviewed and tested.

## Validation
---
*Minor decision*
- **Upgrade previous version** : 
- [x] **Code review** : Kay0u
- [x] **Approval (LGTM)** : Kay0u
- [ ] **Approval (LGTM)** : 
- **CI succeeded** : 
[Build Status](https://ci-apps-hq.yunohost.org/jenkins/job/searx_ynh%20PR45/)  
When the PR is marked as ready to merge, you have to wait for 3 days before really merging it.

### CODE REVIEW

**Comment by maniackcrudelis** [comment]
Don't know if it worth publishing the testing for real tests or not...?

**Comment by JimboJoe** [comment]
Well, I'd say no as it is... that would be more suited with an [upgrade to v0.15](https://github.com/YunoHost-Apps/searx_ynh/pull/41)... :wink:

**Comment by kay0u** [comment]
I'll merge it in 3 days... (9 March /O.O\)

**Comment by kay0u** [comment]
Yolomerge!

**Pull request merged**
