### PR TITLE
Testing

### LINKED ISSUE #23: The panel is in global configuration for the domain (nginx.conf)
Hello, 
I know #10 #11 sort of force you to move the panel inclusion outside of the location section, but this has two consequences:

1) the floating panel is show everywhere on the domain, even on the home page (tiles) where it doubles the existing logo and on the admin page where it is a pain on mobile.
Screenshots as example (disapears if a remove the "include SSOWAT user panel" section)
capture d ecran de 2017-12-06 12-07-05
capture d ecran de 2017-12-06 12-08-09

2)  it can prevent nginx from loading when searx app is used in conjuction with another app that does the same thing. 
For example, I installed movim app [(](https://github.com/movim/movim_ynh/) and when I wanted to  reload nginx, I got this error:

> nginx -t
> nginx: [emerg] "sub_filter" directive is duplicate in /etc/nginx/conf.d/yunohost_panel.conf.inc:2
> nginx: configuration file /etc/nginx/nginx.conf test failed

I already opened a PR at movim to have the panel inclusion part moved, but I don't know what the solution for searx would be, as it doesn't work in either of the location sections.

Thanks for bringing searx to yunohost, by the way!!

### PR DESCRIPTION
**Pull request by maniackcrudelis**
## Problem
- *The fix of old is_public value doesn't work if is_public is in lowercase*
- *Searx can't be installed on stretch*
- *App not up to date*
- *The install on subpath is broken*

## Solution
- *Compare without considering lowercase or uppercase. #25*
- *Modify the dependence python-pybabel to python-babel #28*
- *Upgrade to 0.14.0*
- *Use the uwsgi config from the upstream as documented [here](https://asciimoo.github.io/searx/dev/install/installation.html#with-nginx).*
- Fix #23

## PR Status
Work finished. Package_check, basic tests and upgrade from last version OK.  
Could be reviewed and tested.

## Validation
---
*Minor decision*
- **Upgrade previous version** : 
- [x] **Code review** : frju365
- [x] **Approval (LGTM)** : frju365
- [x] **Approval (LGTM)** : JimboJoe
- **CI succeeded** : [Build Status/badge/icon)](https://ci-apps-dev.yunohost.org/jenkins/job/searx_ynh%20testing%20(Official)/)  
When the PR is mark as ready to merge, you have to wait for 3 days before really merge it.

### CODE REVIEW

**Comment by maniackcrudelis** [comment]
Ready to be reviewed

**Comment by maniackcrudelis** [comment]
Upgrade fails, this PR have to wait for https://github.com/YunoHost-Apps/searx_ynh/pull/31 before going forward...

**Comment by JimboJoe** [comment]
CI test re-launched, waiting for it to advertise the testing.

**Comment by maniackcrudelis** [comment]
I don't reproduce the 504 error on my VM. Maybe this new version is a little bit longer to start.
We should try to add the helper to check the boot of the service.

**Comment by JimboJoe** [comment]
Yes, waiting for the effective end of start would be better.
But for now, since you confirm it runs OK on your VM, I think we could release this testing.
Up to you!

**Comment by maniackcrudelis** [comment]
Actually, I know that I have no time right now to do this modification. But I'm worried that we'd forget to fix that if we don't now.
I could have a look at it on Friday, what do you think about waiting until then ?

**Comment by JimboJoe** [comment]
It's only in 3 days, so we really can wait :grinning:

**Comment by frju365** [comment]
For me code review, LGTM ok. Just waiting a correct build of the CI ;)

**Comment by maniackcrudelis** [comment]
https://github.com/YunoHost-Apps/searx_ynh/pull/33

**Comment by alexAubin** [comment]
Bumpity bump, anybody has some courage to work on searx ? This PR is opened since two months :s

**Comment by trillerpfeife** [comment]
Also would like to use searx, at least get the python-pybabel #27 fixed. https://github.com/YunoHost-Apps/searx_ynh/pull/30/files#diff-ad962c6fd65b725b71aa46c8a715127fL58

**Comment by JimboJoe** [comment]
As I stated earlier, I'm OK with releasing this testing to at least have a "public" workaround.
It would have been awesome if @trillerpfeife tested this release.
This is the first case of a PR which is working fine, but freaking the CI out...

**Comment by maniackcrudelis** [comment]
> anybody has some courage to work on searx ?

Work is (sometimes) ongoing on [this PR](https://github.com/YunoHost-Apps/searx_ynh/pull/33), but I couldn't find a fix so far.

**Comment by maniackcrudelis** [comment]
Sorry, seems that I forgot this testing...
Since that there's a lot of new commits, I dismiss the previous reviews from Josue-T and frju365.

This is now ready to be reviewed again ;)

**Comment by maniackcrudelis** [comment]
Also, since most of the commits are from me or Josue-T, I think we should expect reviews mainly from @JimboJoe and @frju365.

**Pull request merged**
