### PR TITLE
Fix upgrade

### PR DESCRIPTION
**Pull request by maniackcrudelis**
## Problem
- *Upgrade fails with error: "ImportError: No module named _internal"*

## Solution
- *Do not reinstall pip to avoid a conflict between pip versions.*

## PR Status
Work finished. Package_check, basic tests and upgrade from last version OK.  
Could be reviewed and tested.

## Validation
---
*Minor decision*
- **Upgrade previous version** : 
- [ ] **Code review** : 
- [x] **Approval (LGTM)** : Josué
- [ ] **Approval (LGTM)** : 
- **CI succeeded** : [Build Status/badge/icon)](https://ci-apps-dev.yunohost.org/jenkins/job/searx_ynh%20fix_upgrade%20(Official)/)  
When the PR is mark as ready to merge, you have to wait for 3 days before really merge it.

### CODE REVIEW

**Comment by maniackcrudelis** [comment]
Huh, yes it is.
I probably cloned this PR to made the other one, in order to try the upgrade.

**Comment by JimboJoe** [comment]
So, as the other one will get merged, are you OK with closing this one?

**Comment by maniackcrudelis** [comment]
Yes, we can close this one as we merge the other one.

**Comment by JimboJoe** [comment]
Closing this PR as #32 got merged.

**Comment by frju365** [comment]
I didn't understand, why merging this... or what did you mean by "close" . :-??

**Comment by JimboJoe** [comment]
Well I actually closed it, but the two PR seem linked somehow (14 update branch was probably created from fix_upgrade branch), hence that surprising "JimboJoe merged commit 284b297 into testing ".

**Pull request merged**
